
language: ruby
services:
  - docker
env:
  - DOCKER_REGISTRY=registry.cn-shenzhen.aliyuncs.com DOCKER_REPO=tvrcgo/shadowsocks
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
  - docker build -t "$DOCKER_REGISTRY/$DOCKER_REPO:latest" .
  - docker push $DOCKER_REGISTRY/$DOCKER_REPO:latest
