name: Build shadow image

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: tvrcgo/deploy-to-docker@v0.1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ secrets.DOCKER_USER }}/shadow

