name: Docker deployment

on:
  push:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker hub
      uses: tvrcgo/deploy-to-docker@master
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ secrets.DOCKER_REPO }}
        tag: ${{ github.ref_name }}

    - name: Aliyun Registry
      uses: tvrcgo/deploy-to-docker@master
      with:
        registry: registry.us-west-1.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_PASS }}
        repository: ${{ secrets.DOCKER_REPO }}
        tag: ${{ github.ref_name }}
